-- MySQL Script generated by MySQL Workbench
-- Mon Apr 18 17:16:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anaglicia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anaglicia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anaglicia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `anaglicia` ;

-- -----------------------------------------------------
-- Table `anaglicia`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`categorias` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anaglicia`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`estados` (
  `id_estado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `id_estado_UNIQUE` (`id_estado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anaglicia`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`cidades` (
  `id_cidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `fk_estado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cidade`),
  UNIQUE INDEX `id_cidade_UNIQUE` (`id_cidade` ASC) VISIBLE,
  INDEX `fk_cidades_estados1_idx` (`fk_estado` ASC) VISIBLE,
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`fk_estado`)
    REFERENCES `anaglicia`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anaglicia`.`enderecos_residenciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`enderecos_residenciais` (
  `id_endereco_res` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `fk_cidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_endereco_res`),
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco_res` ASC) VISIBLE,
  INDEX `fk_enderecos_cidades1_idx` (`fk_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_cidades1`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `anaglicia`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anaglicia`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`usuarios` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `pessoa_juridica` TINYINT NULL DEFAULT 0,
  `cpf/cnpj` VARCHAR(14) NOT NULL,
  `telefone_1` VARCHAR(10) NOT NULL,
  `telefone_2` VARCHAR(10) NULL,
  `nome_usuario` VARCHAR(80) NULL,
  `senha` TEXT NULL,
  `nivel_acesso` ENUM('cliente', 'administrador') NULL DEFAULT 'cliente',
  `fk_endereco_residencial` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf/cnpj` ASC) VISIBLE,
  INDEX `fk_clientes_enderecos_residenciais1_idx` (`fk_endereco_residencial` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_enderecos_residenciais1`
    FOREIGN KEY (`fk_endereco_residencial`)
    REFERENCES `anaglicia`.`enderecos_residenciais` (`id_endereco_res`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anaglicia`.`enderecos_obras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`enderecos_obras` (
  `id_endereco_obra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `fk_cidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_endereco_obra`),
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco_obra` ASC) VISIBLE,
  INDEX `fk_enderecos_cidades1_idx` (`fk_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_cidades10`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `anaglicia`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anaglicia`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anaglicia`.`projetos` (
  `id_projeto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(80) NOT NULL,
  `area_terreno` VARCHAR(6) NOT NULL,
  `area_construida` VARCHAR(6) NOT NULL,
  `tipologia` VARCHAR(150) NOT NULL,
  `url_img_1` VARCHAR(500) NOT NULL,
  `url_img_2` VARCHAR(500) NOT NULL,
  `url_img_3` VARCHAR(500) NOT NULL,
  `url_img_4` VARCHAR(500) NOT NULL,
  `url_img_5` VARCHAR(500) NOT NULL,
  `fk_categoria` INT UNSIGNED NOT NULL,
  `fk_endereco_obra` INT UNSIGNED NOT NULL,
  `fk_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_projeto`),
  UNIQUE INDEX `id_projeto_UNIQUE` (`id_projeto` ASC) VISIBLE,
  INDEX `fk_projetos_categorias_idx` (`fk_categoria` ASC) VISIBLE,
  INDEX `fk_projetos_enderecos_obras1_idx` (`fk_endereco_obra` ASC) VISIBLE,
  INDEX `fk_projetos_clientes1_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_categorias`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `anaglicia`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_enderecos_obras1`
    FOREIGN KEY (`fk_endereco_obra`)
    REFERENCES `anaglicia`.`enderecos_obras` (`id_endereco_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_clientes1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `anaglicia`.`usuarios` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
